services:
  homeserver-rust:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    stdin_open: true
    container_name: homeserver-rust
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "8081:8081"
    environment:
      - TZ=${TZ:-Asia/Kolkata}
      - CONFIG_FILE=/app/config/application.toml
      - RUST_LOG=info
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config/application.toml
      - /var/run/docker.sock:/var/run/docker.sock
